### PR TITLE
Update baseimg from nvidia/cudagl to nvidia/cuda

### PR DESCRIPTION
**Pull request by patrick-5546**
The Docker image `nvidia/cudagl` has been deprecated and replaced with `nvidia/cuda`. The new image has the updated cuda repo signing key so that `sudo apt update` works, but deprecates some tags: see the Announcement section of https://hub.docker.com/r/nvidia/cuda for more details, and #276 for some context.

What I did is replace every instance of `cudagl` with `cuda` in the codebase.

### References
- New cuda image: https://hub.docker.com/r/nvidia/cuda
- Original/deprecated cuda image: https://hub.docker.com/r/nvidia/cudagl

### CODE REVIEW

**Comment by slonopotamus** [comment]
I wonder what do we do with `nvidia/opengl`...

**Comment by slonopotamus** [comment]
WRT CI failure, looks like we hit https://github.com/docker/docker-py/issues/3113

**Comment by russkel** [comment]
Thanks @patrick-5546

**Comment by slonopotamus** [comment]
Could you please rebase onto latest `master` branch, so that CI tries to run again?

**Comment by russkel** [comment]
@patrick-5546 I seem to be getting issues with it not finding a suitable Vulkan surface renderer when it tries to bring up the editor interface. It compiles the shaders fine but after that it fails.

Have you run 5.0+ with the CUDA base image?

**Comment by russkel** [comment]
Okay so there is no vulkan support in the CUDA image.

**Comment by russkel** [comment]
This is my attempt at a fix:
https://github.com/Greenroom-Robotics/ue4-docker/commit/b8bd15277930d7bc35ba5f8b1233be04009caddc

**Comment by patrick-5546** [comment]
> Edit: I found we have to do the following apt install https://gitlab.com/nvidia/container-images/vulkan/-/blob/master/docker/Dockerfile.ubuntu#L28 to get it to report the vulkan devices properly.

I believe I also had to install `vulkan-utils` to get it working on ue4.

**Comment by russkel** [comment]
> > Edit: I found we have to do the following apt install https://gitlab.com/nvidia/container-images/vulkan/-/blob/master/docker/Dockerfile.ubuntu#L28 to get it to report the vulkan devices properly.
> 
> I believe I also had to install `vulkan-utils` to get it working on ue4.

Okay good to know. Maybe I will make a PR for this. Now called `vulkan-tools`.

**Pull request merged**
