### PR TITLE
Use dotnet SDK 4.8

### PR DESCRIPTION
**Pull request by galeone**
In this way, we can create the images on Windows server updated with the February 2020 patch.
Fixes https://github.com/adamrehn/ue4-docker/issues/73

### CODE REVIEW

**Comment by adamrehn** [comment]
Have you tested this change for both source builds ([ue4-engine](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-engine)) and Installed Builds ([ue4-full](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-full)) of all of the versions of the Unreal Engine that ue4-docker is compatible with (4.19.2, 4.20.3, 4.21.2, 4.22.3, 4.23.1, 4.24.3) to ensure that it works correctly for all of them and does not break backwards compatibility with the older Engine versions?

**Comment by galeone** [comment]
I don't have the required hardware to test all of them (it takes really **a lot** of time and storage building windows containers), I'm sorry. I tested with 4.23.1 and 4.24.3 and in both cases, I was able to build ue4-engine and ue4-full images.

**Comment by adamrehn** [comment]
Yes, it certainly takes quite a lot of CPU horsepower and disk space, which is why updates to the Windows container images always take me much longer to validate than the Linux images. I'll test out each of those configurations myself over the coming week or so to make sure everything works before I merge this pull request.

**Comment by galeone** [comment]
Thank you very much for your efforts in maintaining this project :+1:

**Comment by adamrehn** [comment]
After running test builds pretty much around the clock for the past few days, I've managed to verify that this change is compatible with all six of the currently supported versions of the Unreal Engine and that everything builds happily.

**Pull request merged**
