### PR TITLE
Local ue4 source support and configurable tmp folder

### PR DESCRIPTION
**Pull request by jit-rc**
Unreal Engine can now be added from local copy, either a directory or Release archive file on the host machine using the argument  --ue-src 

tmp folder might require more space than might be available on normal OS tmp folder, to override that, now we can use --tmp-dir

### CODE REVIEW

**Comment by adamrehn** [comment]
@jit-rc could you please describe the use case(s) that would benefit from working with source code from the host filesystem rather than a version control system?

The most obvious scenario I can envisage where code isn't checked into version control is when a developer is testing Engine modifications prior to committing them, but that use case would be far better served by performing incremental builds in an interactive container that bind-mounts the Unreal Engine source tree, rather than performing builds in a Dockerfile.

(I also realise that copying from the host filesystem could be used as a stop-gap solution for working with currently unsupported version control systems such as Perforce, but implementing proper support for those systems would be the correct solution in that case.)

**Comment by jit-rc** [comment]
I was making the docker for https://github.com/carla-simulator/carla/tree/0.9.6/Util/Docker and don't need to change the UE code. The issue was github authentication would not work with 2-factor, and I was building the docker on a server with more storage than my laptop and didn't want to store and of my credentials there, it seemed simpler to share the downloaded release archive. Did it for my organizations use and shared it back if you feel that it could help others

**Comment by adamrehn** [comment]
GitHub two-factor authentication actually [can be used with ue4-docker](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#specifying-git-credentials) if you generate a personal access token and specify the token in place of a password. (See issue #22.)

I'm hesitant to add yet another Dockerfile to ue4-docker in its current state, since the build infrastructure was only originally designed for a small number of images and has already gotten a little messy as I've split images and added new ones. That being said, I'd like to be able to accommodate a wider variety of configurations in the future, with the option for users to customise the process to a far greater extent than is currently possible. I've started a brainstorming discussion in issue #48 to start the ball rolling on a refactor of ue4-docker that would make the integration of functionality such as that presented in this pull request feasible in a clean way.

**Comment by jit-rc** [comment]
Yes, I know about the personal access token, I didn't want to create and share that too on our shared server, though it is private server. I understand your hesitation and agree that there are too many docker files and redundancies  for windows and linux, let me just keep the changes on my local branch and you can close the PR without merging.

**Pull request closed without merging**
